### ISSUE TITLE
Northpole-up-knappen flyttar kartans position

### ISSUE THREAD

**Issue by Rovanion** [WeatherMagic/weather-front#43]
Den borde endast korrigera rotationen.

**Comment by majil334** [comment]
Vi jobbar på det från pointer-zoom-branchen

**Comment by Rovanion** [comment]
Känns typiskt som att det inte har att göra med zoomning till pekaren utan bör vara sin egna branch - egentligen är det väl mitt fel att jag godkände PR:en allt för ivrigt men.

**Comment by majil334** [comment]
Jag fattade det som att vi hade en diskussion kring nortpole-up och att vi sa att det jag la upp var bra nog. Denna funktion att hålla koll på vart som är nordpolen vill vi dock använda i zoom-pointer också. Det ska bli sin egen branch men vi gör det jobbiga jobbet i zoom-pointer.

**Comment by Rovanion** [comment]
Nej jag tar helt på mig att jag misslyckats kommunicera här. flåt
